#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GraceOfGuru.Resource", IsApplication=true)]

namespace GraceOfGuru
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int fab_margin = 2130837504;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int Aam = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Aam_txt = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int Ainak = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Batak = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int Bharath = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int Chaata = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int Dus = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int Gamla = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int hindialphabet = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int homeIcon = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int leftIcon = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int Makaan = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int matar = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int onclickactivities_u5 = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int rightIcon = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int soundIcon = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int Taala = 2130903056;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Font
		{
			
			// aapt resource value: 0x7F040000
			public const int hindifont = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int hindifontdisplay = 2130968577;
			
			static Font()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Font()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int action_settings = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int buttonHome = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int buttonNext = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int buttonPrev = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int buttonSound = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int button_Aa = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int button_Ai = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int button_Ba = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int button_Bha = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int button_cha = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int button_Da = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int button_Ga = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int button_Ma = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int button_Ta = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int callGraph = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int clearCache = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int grace = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int graphData = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int GuessEnglishWords = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int HindiVarnamala = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int imageView1 = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int login = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int MatchingGame = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int messageDisplay = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int textForAam = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int username = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int welcome = 2131034138;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int activity_main = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int content_main = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int FlashCards = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int HindiVarnamala = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int layout1 = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int layout2 = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int Main = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int variousOptionsForKids = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int varnamala_table = 2131099656;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F070000
			public const int menu_main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F080000
			public const int ic_launcher = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int ic_launcher_foreground = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int ic_launcher_round = 2131230722;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F090000
			public const int Aam = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int Ainak = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int Batakh = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int Bharath = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int Chaata = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int Dus = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int Gamla = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int Matar = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int Taala = 2131296264;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0000
			public const int action_settings = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int app_name = 2131361793;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public const int AppTheme = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int AppTheme_AppBarOverlay = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int AppTheme_NoActionBar = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int AppTheme_PopupOverlay = 2131427331;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
